apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gkp
  name: gkp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gkp
  template:
    metadata:
      labels:
        app: gkp
    spec:
      containers:
      - name: gkp
        image: videmsky/golang-k8s-prometheus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
