apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gkp
  name: gkp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gkp
  template:
    metadata:
      labels:
        app: gkp
    spec:
      containers:
      - name: gkp
        image: index.docker.io/videmsky/golang-k8s-prometheus:latest
        env:
          - name: APPLICATION_NAME
            value: gkp
        ports:
        - name: web
          containerPort: 8889
