version: v1
kind: kubernetes
application: gkp
targets:
  prod:
    account: lotctl
    namespace: gkp-prod
    strategy: trafficSplit
    constraints:
      beforeDeployment:
        - pause:
            untilApproved: true
manifests:
  - path: https://raw.githubusercontent.com/videmsky/golang-k8s-prometheus/main/manifests/deployment.yml
  - path: https://raw.githubusercontent.com/videmsky/golang-k8s-prometheus/main/manifests/service.yml
  - path: https://raw.githubusercontent.com/videmsky/golang-k8s-prometheus/main/manifests/prod-namespace.yml
    targets: ["prod"]
strategies:
  trafficSplit:
    canary:
      steps:
        - setWeight:
            weight: 25
        - exposeServices:
            services:
              - gkp-service
            ttl:
              duration: 30
              unit: minutes
        - pause:
            untilApproved: true
        - setWeight:
            weight: 100