name: build, test, & publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -cover ./...

  release-image:
    runs-on: ubuntu-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker Image
      run: |
        export IMAGE_NAME=$GITHUB_REPOSITORY
        export TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)
        docker build -t $IMAGE_NAME:$TAG .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $IMAGE_NAME:$TAG
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}






